### ISSUE TITLE
Repeated stacktraces in nova-novncproxy.log

### ISSUE THREAD

**Issue by pbannister** [blueboxgroup/ursula#1099]
The log file `/var/log/nova/novncproxy.log` is full of stack traces, on two(?) second intervals.

For example:

```
2015-07-30 03:32:16.178 19334 DEBUG nova.console.websocketproxy [-] 172.16.0.100: new handler Process vmsg /opt/bbc/openstack-10.0-bbc72/nova/local/lib/python2.7/site-packages/websockify/websocket.py:828
2015-07-30 03:32:16.186 17127 INFO nova.console.websocketproxy [-] handler exception: [Errno 104] Connection reset by peer
2015-07-30 03:32:16.188 17127 DEBUG nova.console.websocketproxy [-] exception vmsg /opt/bbc/openstack-10.0-bbc72/nova/local/lib/python2.7/site-packages/websockify/websocket.py:828
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy Traceback (most recent call last):
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy   File "/opt/bbc/openstack-10.0-bbc72/nova/local/lib/python2.7/site-packages/websockify/websocket.py", line 878, in top_new_client
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy     client = self.do_handshake(startsock, address)
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy   File "/opt/bbc/openstack-10.0-bbc72/nova/local/lib/python2.7/site-packages/websockify/websocket.py", line 813, in do_handshake
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy     self.RequestHandlerClass(retsock, address, self)
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy   File "/opt/bbc/openstack-10.0-bbc72/nova/local/lib/python2.7/site-packages/nova/console/websocketproxy.py", line 150, in __init__
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy     websockify.ProxyRequestHandler.__init__(self, *args, **kwargs)
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy   File "/opt/bbc/openstack-10.0-bbc72/nova/local/lib/python2.7/site-packages/websockify/websocket.py", line 112, in __init__
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy     SimpleHTTPRequestHandler.__init__(self, req, addr, server)
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy   File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy     self.handle()
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy   File "/opt/bbc/openstack-10.0-bbc72/nova/local/lib/python2.7/site-packages/websockify/websocket.py", line 540, in handle
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy     SimpleHTTPRequestHandler.handle(self)
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy     self.handle_one_request()
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy     method()
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy   File "/opt/bbc/openstack-10.0-bbc72/nova/local/lib/python2.7/site-packages/websockify/websocket.py", line 510, in do_GET
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy     SimpleHTTPRequestHandler.do_GET(self)
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy   File "/usr/lib/python2.7/SimpleHTTPServer.py", line 44, in do_GET
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy     f = self.send_head()
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy   File "/usr/lib/python2.7/SimpleHTTPServer.py", line 94, in send_head
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy     self.send_response(200)
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy   File "/usr/lib/python2.7/BaseHTTPServer.py", line 395, in send_response
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy     self.send_header('Server', self.version_string())
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy   File "/usr/lib/python2.7/BaseHTTPServer.py", line 401, in send_header
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy     self.wfile.write("%s: %s\r\n" % (keyword, value))
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy   File "/usr/lib/python2.7/socket.py", line 324, in write
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy     self.flush()
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy   File "/usr/lib/python2.7/socket.py", line 303, in flush
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy     self._sock.sendall(view[write_offset:write_offset+buffer_size])
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy   File "/opt/bbc/openstack-10.0-bbc72/nova/local/lib/python2.7/site-packages/eventlet/greenio.py", line 359, in sendall
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy     tail = self.send(data, flags)
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy   File "/opt/bbc/openstack-10.0-bbc72/nova/local/lib/python2.7/site-packages/eventlet/greenio.py", line 342, in send
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy     total_sent += fd.send(data[total_sent:], flags)
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy error: [Errno 104] Connection reset by peer
2015-07-30 03:32:16.188 17127 TRACE nova.console.websocketproxy 
2015-07-30 03:32:16.196 19334 DEBUG nova.console.websocketproxy [-] Reaing zombies, active child count is 0 vmsg /opt/bbc/openstack-10.0-bbc72/nova/local/lib/python2.7/site-packages/websockify/websocket.py:828
```

I got to this point by pulling down the current `ursula` and bringing up an `allinone` instance. Running `tail -f /var/log/nova/*.log` is mostly dominated by these stack traces.

Flat admission: I have no notion if this is an OpenStack/Juno problem, a Ursula configuration problem, or something about my setup. (Though the last _seems_ unlikely.)

Monitoring log files is a simple diagnostic during development. Noise in the logs can make than diagnostic less useful. At some point, we want to whack down the worst noise. (Have to start somewhere.)

**Comment by j2sol** [comment]
Is this still happening? We're now on kilo.

**Comment by pbannister** [comment]
Ursula is on Kilo? Good news, and timely. Will check... (might take a bit).
