### ISSUE TITLE
[MongoDB] create admin user fails when ucarp resides on controller2 during initial deployment

### ISSUE THREAD

**Issue by CullenTaylor** [blueboxgroup/ursula#1256]
During initial deployment, when controller2 is where ucarp is create admin user fails as it is assuming controller1 is always master db. The ansible error is detailed below. Ddaskal should be able to debug and elaborate further.

```
TASK: [mongodb-server | create admin user] ************************************
Friday 09 October 2015  23:57:27 +0000 (0:00:00.384)       0:03:50.104 ********
skipping: [controller2]
failed: [controller1] => {"failed": true, "parsed": false}
OpenSSH_5.9p1 Debian-5ubuntu1.7, OpenSSL 1.0.1 14 Mar 2012
debug1: Reading configuration data /root/.ssh/config
debug1: /root/.ssh/config line 1: Applying options for controller1
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Traceback (most recent call last):
 File "<stdin>", line 1858, in <module>
 File "<stdin>", line 239, in main
 File "<stdin>", line 143, in user_add
 File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 871, in add_user
   (not uinfo["users"]), name, password, read_only, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 793, in _create_or_update_user
   self.command(command_name, name, **opts)
 File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 454, in command
   codec_options, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 366, in _command
   allowable_errors)
 File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 189, in command
   self._raise_connection_failure(error)
 File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 316, in _raise_connection_failure
   raise error
pymongo.errors.NotMasterError: not master


TASK: [mongodb-server | add mongodb secondary servers to replica set] *********
Friday 09 October 2015  23:57:28 +0000 (0:00:00.650)       0:03:50.755 ********
changed: [controller2]
```

**Comment by ddaskal** [comment]
Opened PR#1261 to resolve this issue - https://github.com/blueboxgroup/ursula/pull/1261

**Comment by ddaskal** [comment]
PR fix merged. Please close this issue
